version: "3"
services:
  db:
    container_name: asana_admin.db
    image: postgres
    networks:
        - asana_admin
    environment:
      - POSTGRES_USER=devpostgres
      - POSTGRES_PASSWORD=postgres
  app:
    container_name: asana_admin.app
    build: .
    volumes:
      - .:/asana_admin
    ports:
      - "8000:8000"
    expose:
      - 8000
    networks:
      - asana_admin
    depends_on: 
      - db
    env_file:
      - .env
    command: /bin/bash ./build.sh

volumes:
  postgres_data:

networks:
  asana_admin:
