version: "3"
services:
  app:
    container_name: app
    build: .
    volumes:
      - .:/asana_admin
    ports:
      - "8000:8000"
    expose:
      - 8000
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
